name: manage-azure-policy-a528295f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'mipolicy/policies/Deploy_Long_term_backup_retention_policy_to_Managed_Instance_Databases_5f6cf7ba-c1cc-48a5-9c5d-3f3dc98abd43/**'
#      - .github/workflows/manage-azure-policy-a528295f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a528295f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          mipolicy/policies/Deploy_Long_term_backup_retention_policy_to_Managed_Instance_Databases_5f6cf7ba-c1cc-48a5-9c5d-3f3dc98abd43/**
